### ISSUE TITLE
Styles missing

### ISSUE THREAD

**Issue by furai** [LLNL/HPC-Tutorials#11]
Hello,

I come from the https://hpc-tutorials.llnl.gov/posix/
It seems that styles on this page are broken because of issues with https://icsmaint-ext.llnl.gov/ site which is throwing 503s.

Is it something on my side only? 

Best regards,
Furai

**Comment by gonsie** [comment]
Hi @furai,
Could you check if the issue still exists? We have recently updated the styles for this site. Thanks!

**Comment by furai** [comment]
Yeah, I saw it a week or so ago, it works now. Thanks!
